import { ArrowRight } from "lucide-react";

export const features = [
  {
    title: "AI-Powered Content Generation",
    description: "Create engaging social media posts in seconds using advanced AI technology.",
    icon: ArrowRight,
  },
  {
    title: "Customizable Templates",
    description: "Tailor content to fit your brand’s voice, style, and audience.",
    icon: ArrowRight,
  },
  {
    title: "Social Media Optimized",
    description: "Ensure your posts are optimized for engagement on all major platforms.",
    icon: ArrowRight,
  },
  {
    title: "Time-Saving",
    description: "Save hours on content creation and focus on engaging with your audience.",
    icon: ArrowRight,
  },
];

export const testimonials = [
  {
    name: "Sophia L.",
    role: "Influencer & Content Creator",
    quote: "This tool has made content creation effortless. I can focus more on engaging with my followers!",
  },
  {
    name: "Mark T.",
    role: "Social Media Manager",
    quote: "The AI-generated posts are creative and tailored to my audience. My engagement rates have improved significantly.",
  },
  {
    name: "Lisa R.",
    role: "Brand Consultant",
    quote: "The customizable templates help me keep content fresh and on-brand every time.",
  },
];

export const tiers = [
  {
    name: "Free",
    price: "$0",
    features: [
      "5 posts per month",
      "Pre-designed templates",
      "Basic customization",
      "Standard support",
    ],
  },
  {
    name: "Pro",
    price: "$10",
    features: [
      "50 posts per month",
      "Custom templates and requirements",
      "Advanced customization",
      "Priority support",
      "Exclusive content templates",
    ],
  },
];

export const topics = [
  "Instagram",
  "TikTok",
  "Twitter",
  "Facebook",
  "YouTube",
];

export const durations = [
  "Short Posts",
  "Medium-Length Posts",
  "Long-Form Posts",
];

export const studentLevels = [
  "No Experience",
  "Beginner Content Creator",
  "Intermediate Influencer",
  "Advanced Content Creator",
  "Social Media Expert",
];

export const subtopics = {
  Instagram: [
    "Instagram Feed Posts",
    "Instagram Stories",
    "Instagram Reels",
    "Influencer Marketing",
    "Hashtag Strategy",
    "Branding & Aesthetics",
    "Instagram Ads",
    "Engagement Tactics",
    "Content Calendar",
    "Analytics & Insights",
  ],
  TikTok: [
    "TikTok Videos",
    "TikTok Challenges",
    "TikTok Ads",
    "Viral Trends",
    "Hashtag Strategy",
    "Engagement Tips",
    "TikTok Analytics",
    "TikTok Influencers",
    "Content Creation Tips",
    "TikTok Stories",
  ],
  Twitter: [
    "Twitter Threads",
    "Hashtag Optimization",
    "Engagement Boosting Tips",
    "Twitter Ads",
    "Viral Tweets",
    "Twitter Polls",
    "Brand Voice on Twitter",
    "Audience Engagement",
    "Trending Topics",
    "Content Calendar for Twitter",
  ],
  Facebook: [
    "Facebook Posts",
    "Facebook Ads",
    "Engagement Strategies",
    "Facebook Stories",
    "Content for Facebook Groups",
    "Analytics & Insights",
    "Facebook Video Strategy",
    "Organic Reach Strategies",
    "Facebook Marketing Trends",
    "Facebook Ads Targeting",
  ],
  YouTube: [
    "YouTube Video Scripts",
    "Video Descriptions and Tags",
    "SEO for YouTube",
    "Video Thumbnails",
    "Engagement Tactics on YouTube",
    "YouTube Monetization",
    "Video Editing Tips",
    "YouTube Shorts",
    "Content Planning",
    "Analytics & Growth on YouTube",
  ],
};

export const faqItems = [
  {
    question: "How accurate is the content generated by the AI?",
    answer:
      "The accuracy of the content generated by the AI depends on the input you provide. The more specific the details, the more relevant the content. You should always review the generated content to ensure it aligns with your brand's voice and goals.",
  },
  {
    question: "Can I customize the content generated by the AI?",
    answer: "Yes, you can fully customize the content to align with your personal or brand's style. Advanced customization options are available for Pro users.",
  },
  {
    question: "What social media platforms are supported?",
    answer:
      "The content generator supports all major platforms including Instagram, TikTok, Facebook, Twitter, and YouTube. Each post will be optimized according to the best practices for the respective platform.",
  },
  {
    question: "How long does it take to generate content?",
    answer:
      "The AI can generate content in about 30 seconds to a minute, depending on the complexity and length of the post. Customization options may take slightly longer.",
  },
  {
    question: "Can I use the generated content for paid campaigns?",
    answer:
      "Yes, you can use the generated content for organic posts, paid campaigns, or influencer marketing. Just make sure to adjust it according to the platform’s best practices and your campaign’s goals.",
  },
];
